services:
  dependencies_installation:
    image: ambientum/php:8.0-nginx
    command: bash /app/docker/dependencies/docker-dependencies.sh
    volumes:
      - ./:/app
    networks:
        - mysql-network
    depends_on: 
        - mysql
        
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 
      MYSQL_HOST: localhost
    volumes: 
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - mysql-network
    ports:
      - "3306:3306"
networks: 
  mysql-network: 
    driver: bridge